### ISSUE TITLE
Create Overview Aggregate Status Cards

### ISSUE THREAD

**Issue by priley86** [priley86/miq_v2v_ui_plugin#150]
Per the new UX @serenamarie125 @vconzola, we would like to create aggregate status Cards for Infrastructure Mapping and Plan Mappings. The existing APIs should support this, but would like to confirm design/UX. @vconzola can you post a screenshot of envisioned UX?

**Comment by serenamarie125** [comment]
@priley86 is this issue just around the display of information via the agg status cards?  I'd suggest we create another issue which handles the link behavior, which sets a filter for the plans card.  Does that make sense ?

**Comment by priley86** [comment]
will await @vconzola 's mocks... i was guessing based on the new "top level" aggregate status cards - but will wait for further review...

Essentially it would be nice to break the three new sections (top Status Cards (aggregate status) / Migration Plan cards / Infra Mapping list into three different stories... Filters will integrate closely w/ Migration Plan it looks like? Will wait for confirmation...

**Comment by vconzola** [comment]
@priley86 @michaelkro Here's a link to the doc with behavioral details: https://docs.google.com/presentation/d/1MxPiOHkScBeVndabrgqoNSbyi6U8dbHUWrBmm-Xgngo/edit?usp=sharing

**Comment by michaelkro** [comment]
> per Bill, we want to use the `/api/service_templates?type = servicetemplatetransformationplan` to drive the aggregate counts on the plan… the status on that response will indicate `queued, approved, failed, complete` … once created, the plan does not change… and can be reused

**Comment by michaelkro** [comment]
Discovered a detail that needs design/UX guidance.
On the Overview page, we poll for updates to all the transformation/migration plans every 15 sec.  This means that the aggregate cards will go into the loading state (show a spinner) every 15 seconds, which seems non optimal.  I was experimenting, and found a way to only show the loading spinner only when either:
* the page is first visited
* after a hard refresh

Otherwise, loading happens in the background.  If there is an update to the aggregate info, I animated the drop shadow to inform the user.

In any case, we can do whatever you think is appropriate @vconzola @serenamarie125 

## Demo:  Animation when data changes (sorry about the lo-fi gif, please see next gif)
![highlight](https://user-images.githubusercontent.com/15141412/38306650-43f95152-37df-11e8-9efa-7aa1877f9971.gif)

## Demo:  Hi-fi animation
![highlight2](https://user-images.githubusercontent.com/15141412/38306762-91503a56-37df-11e8-905f-ceeb1e7af05d.gif)

**Comment by vconzola** [comment]
@michaelkro We definitely don't want to show the spinner every 15 seconds. I like your proposals for only showing it on page load and hard refresh. I'm also OK with the animated drop shadow when information is updated, but don't know if it adheres to PF guidelines. @serenamarie125 What do you think?  If it's not PF OK, then just update the count as appropriate and don't inform the user.

**Comment by priley86** [comment]
Closed by #196
