### ISSUE TITLE
Toast notification disappearing too quickly after successful migration

### ISSUE THREAD

**Issue by vconzola** [priley86/miq_v2v_ui_plugin#275]
When a plan completes successfully the toast notification is supposed to appear for 8 seconds or until the user interacts with it.  Currently, the toast seems to disappear as soon as the plan migration card is  closed and the aggregate status card is updated.

**Comment by AllenBW** [comment]
Just timed it, success toasts without interaction do indeed last a full 8 seconds on the screen.  That being said, @vconzola if yah don't feel that's long enough we can increase the number [here](https://github.com/AllenBW/miq_v2v_ui_plugin/blob/08b8a52c9af7d9189bf5bf1cba6f7de5e1bcee84/app/javascript/react/screens/App/Overview/Overview.js#L132).

**Comment by vconzola** [comment]
@AllenBW Definitely not what I'm seeing. I'll try to record and post here sometime today.

**Comment by mturley** [comment]
Unassigning myself for now to work on the less confusing #288.

**Comment by vconzola** [comment]
@mturley I have to wrap up some Summit stuff this morning. Will try to reproduce and record it this afternoon. The times I've noticed it have been when I have more than one plan running at a time, if that helps. But this one isn't urgent.

**Comment by AllenBW** [comment]
@michaelkro noticed that orphan notifications occur when there are many piled on at once... It looks like the `onDismiss` action is not being fired, a pfr issue, we're tagging on this to 🔪 💨

**Comment by michaelkro** [comment]
After doing a touch of research, this issue may actually be due to how JS deals with multiple calls to `setInterval`.

My understanding is that b/c JS is single threaded, multiple calls to `setInterval` do not "run in parallel", instead, there is some sort of queue, which includes all the other things the browser is trying to do.

In particular, since we are continually polling, and due to our use of React lifecycle hooks, my suspicion is that our `setInterval` callbacks are having their execution delayed as other processes are being run first (perhaps browser/framework prioritzation?).  This would explain the intermittent and mysterious "quickly disappearing toasts"

Further, I guess it is possible for the context in which the `setInterval` callback is fired to somehow change, which could be a possible explanation for the "lingering toasts".

Anyway, I am not sure of any of this.  Here are my sources

https://softwareengineering.stackexchange.com/questions/314773/does-settimeout-really-execute-in-parallel
https://johnresig.com/blog/how-javascript-timers-work/

**Comment by AllenBW** [comment]
Annnnnnnnnd we gotta fix for this

**Comment by priley86** [comment]
fixed by PR 300 !!!
