### ISSUE TITLE
Migration plan Description Missing

### ISSUE THREAD

**Issue by kedark3** [priley86/miq_v2v_ui_plugin#291]
https://bugzilla.redhat.com/show_bug.cgi?id=1575057

**Comment by priley86** [comment]
per @vconzola - this is working per design.

**Comment by kedark3** [comment]
@priley86 I would like to request @bthurber to look at this issue. I think we should definitely display the description somewhere, why do we take it from user in the first place otherwise?

**Comment by vconzola** [comment]
@kedark3 The description should be visible in the Not Started and Completed plans list views. Right now I see it in the Not Started view, but not the Completed view. This was an omission on my part - I failed to include it in the design mockups. If you aren't seeing the description in the Not Started view, please send a screenshot, since that would be different from what I'm seeing.

Not showing the description in the In Progress card was a design decision to keep the cards uncluttered and allow the user to focus on the more relevant status information.

**Comment by kedark3** [comment]
![image](https://user-images.githubusercontent.com/8180469/39642492-e42c2744-4f9f-11e8-851e-b465f3606db5.png)

**Comment by kedark3** [comment]
![image](https://user-images.githubusercontent.com/8180469/39642504-f1e304c0-4f9f-11e8-837b-5cefd5f915e2.png)

**Comment by kedark3** [comment]
@vconzola this is on Not Started side. Please review.
